### ISSUE TITLE
Error: WARNING: unable to extract uploader nickname

### ISSUE THREAD

**Issue by nitank** [joegesualdo/get-youtube-subtitle-url-node#1]
In the current written function, I tried to catch err using console with the following code- 

function getNonAutoSubs(videoId) {
  return new Promise((resolve, reject) => {
    PythonShell.run('__main__.py', {
      scriptPath: `${__dirname}/youtube-dl/youtube_dl`,
      args: [
        '--write-sub',
        '--skip-download',
        '--sub-format',
        'vtt',
        `https://www.youtube.com/watch?v=${videoId}`],
    }, (err, results) => {
      if (err) {
        console.log('from err', err);
        reject(err);
      } else {
        if (results.indexOf('Default Subtitle:') === -1) {
          console.log('from second err', results);
          reject(new Error(`No subtitles for video: ${videoId} `));
        } else {
          console.log('from third result', results);
          resolve(results[results.indexOf('Default Subtitle:') + 1]);
        }
      }
    });
  });
}
 and so got this error in console - 

type  nonauto
from err { Error: WARNING: unable to extract uploader nickname

    at PythonShell.parseError (/home/nitank/Desktop/nit/node_modules/python-shell/index.js:190:17)
    at terminateIfNeeded (/home/nitank/Desktop/nit/node_modules/python-shell/index.js:98:28)
    at ChildProcess.<anonymous> (/home/nitank/Desktop/nit/node_modules/python-shell/index.js:88:9)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
  executable: 'python',
  options: null,
  script: '/home/nitank/Desktop/nit/node_modules/@joegesualdo/get-youtube-subtitle-url-node/youtube-dl/youtube_dl/
__main__.py',
  args:
   [ '--write-sub',
     '--skip-download',
     '--sub-format',
     'vtt',
     'https://www.youtube.com/watch?v=kcW4ABcY3zI' ],
  exitCode: 0 }
Non auto Subtitles dont exist for kcW4ABcY3zI

Its happening for each and every video which has subtitles on youtube

**Comment by joegesualdo** [comment]
@nitank Can you try again? Hopefully https://github.com/joegesualdo/get-youtube-subtitle-url-node/pull/2 fixed the issue. The new version is `0.1.0`.

**Comment by joegesualdo** [comment]
@nitank Closing this for now. Let me know if you have any other issues.
